version: '3.8'
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api_getway
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.example
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: yarn run start:dev

  user:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: user-app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.example
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: yarn run start:dev

  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: judeRCy5vUXfDmcMcJb2NbRDt
      POSTGRES_DB: test
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_yojad
    environment:
      REDIS_PASSWORD: 'Mu12345'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'

  rabbitmq:
    container_name: whatsapp-rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: EzpuGUh7egUacUgT
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

volumes:
  pgdata:
  redis_data:
    driver: local
